### PR TITLE
retrieve embedding without FetchData

### PR DESCRIPTION
**Pull request by lch14forever**

### CODE REVIEW

**Comment by GuangchuangYu** [comment]
修改版本快，是因为都是直接用`[`去取相应的数据，而`FetchData`有额外的操作，我当前不太清楚这些额外的操作是否有影响。

单纯从函数调用来看，`FetchData`还需要`slot`这个参数，是修改版本所没有的，这是否需要考虑进去？

另外FetchData在整个包中有三处位置，第三个位置也可以看一下。

**Comment by GuangchuangYu** [comment]
@lch14forever any update?

**Comment by lch14forever** [comment]
I confirmed that the PS implementation works in V4 and V5 of Seurat. Two `FetchData` calls were replaced using valid API exposed in `SeuratObject`:
 1.  `SeuratObject::Idents(object)`
 2.  `SeuratObject::Embeddings(object[[reduction]]))`
 
 The `slot` parameter was used for `data`, `scaled.data`, or `counts` (replaced by `layer` in V5) and would not affect these two calls.

**Comment by lch14forever** [comment]
The 3rd `FetchData` retrieves the expression data and is only used when `feature` is provided. I guess we shouldn't change this part to avoid potential issue.

**Pull request merged**
